from __future__ import annotations

from copy import deepcopy
from pathlib import Path

import yaml

from mvp_vertical.hermes_distribution import (
    component_content_digest,
    evaluate,
    file_content_digest,
    route_contract,
    tree_content_digest,
)

ROOT = Path(__file__).resolve().parents[1]
MONOREPO_ROOT = ROOT.parent
LOCK = ROOT / "hermes" / "distribution" / "pantheon-standard.lock.yaml"


def _manifest() -> dict:
    value = yaml.safe_load(LOCK.read_text(encoding="utf-8"))
    assert isinstance(value, dict)
    return value


def test_distribution_lock_keeps_exact_core_separate_and_default_off() -> None:
    manifest = _manifest()
    assert evaluate(manifest, monorepo_root=MONOREPO_ROOT) == []
    assert manifest["revision"] == 3
    assert set(manifest["source_pins"]) == {"pantheon_repository", "hermes_runtime"}
    assert manifest["source_pins"]["pantheon_repository"]["repository"] == (
        "ifanjuang/Pantheon-Next"
    )
    required_kinds = {
        item["kind"] for item in manifest["components"] if item["required"] is True
    }
    assert required_kinds == {"run_binding", "context_bridge", "runtime_observer"}
    assert len(manifest["components"]) == 3
    assert all("source_repository" not in item for item in manifest["components"])
    assert all(item["path"].startswith("implementation/") for item in manifest["components"])
    assert all(item["enabled_by_default"] is False for item in manifest["components"])
    assert all(item["content_digest"].startswith("sha256:") for item in manifest["components"])
    runtime = manifest["source_pins"]["hermes_runtime"]
    assert isinstance(runtime["version"], str) and runtime["version"]
    assert runtime["artifact_digest"] is None
    assert runtime["observation_ref"] == "docs/governance/HERMES_RUNTIME_SURFACE_REVIEW.md"
    assert manifest["state"]["installation_state"] == "not_observed"
    assert manifest["state"]["activation_state"] == "not_activated"
    assert manifest["state"]["task_authorization_state"] == "not_authorized"
    assert manifest["state"]["acceptance_state"] == "not_run"
    assert set(manifest["authority"].values()) == {False}


def test_distribution_digest_algorithms_are_deterministic(tmp_path) -> None:
    file_path = tmp_path / "one.txt"
    file_path.write_bytes(b"one\n")
    assert file_content_digest(file_path) == component_content_digest(file_path, "file")
    tree = tmp_path / "tree"
    (tree / "nested").mkdir(parents=True)
    (tree / "b.txt").write_bytes(b"b")
    (tree / "nested" / "a.txt").write_bytes(b"a")
    first = tree_content_digest(tree)
    assert first == tree_content_digest(tree)
    assert first == component_content_digest(tree, "tree")
    cache = tree / "__pycache__"
    cache.mkdir()
    (cache / "tools.cpython-311.pyc").write_bytes(b"generated bytecode")
    (tree / "generated.pyo").write_bytes(b"generated optimized bytecode")
    (tree / ".DS_Store").write_bytes(b"generated metadata")
    assert tree_content_digest(tree) == first
    (tree / "nested" / "a.txt").write_bytes(b"changed")
    assert tree_content_digest(tree) != first


def test_distribution_route_contract_matches_current_adapter_sources() -> None:
    assert route_contract(_manifest(), MONOREPO_ROOT) == []


def test_distribution_validator_rejects_digest_authority_and_default_enablement() -> None:
    invalid = deepcopy(_manifest())
    invalid["components"][0]["content_digest"] = "sha256:" + "0" * 64
    invalid["components"][0]["enabled_by_default"] = True
    invalid["state"]["activation_state"] = "activated"
    invalid["authority"]["dispatches_runs"] = True
    errors = evaluate(invalid, monorepo_root=MONOREPO_ROOT)
    assert any(error.startswith("component run-binding digest mismatch:") for error in errors)
    assert "component must remain default-off: run-binding" in errors
    assert "distribution lock must not activate a binding" in errors
    assert "distribution lock claims authority: dispatches_runs" in errors


def test_active_validator_refuses_legacy_revision_and_path_escape() -> None:
    legacy = deepcopy(_manifest())
    legacy["revision"] = 2
    assert "active distribution validator supports revision 3 only" in evaluate(
        legacy, monorepo_root=MONOREPO_ROOT
    )

    escaped = deepcopy(_manifest())
    escaped["components"][0]["path"] = "../outside.py"
    errors = evaluate(escaped, monorepo_root=MONOREPO_ROOT)
    assert "component run-binding escapes Pantheon monorepo root" in errors


def test_distribution_components_keep_translation_observation_without_authority() -> None:
    manifest = _manifest()
    expected_capabilities = {
        "run-binding": {
            "reserve-admitted-launch",
            "submit-one-external-run",
            "record-runtime-start",
            "record-runtime-return",
            "record-typed-project-variant-return",
            "notify-role-trace-attachment",
        },
        "context-bridge": {
            "read-admitted-context",
            "read-admitted-entity",
            "protect-model-bound-context",
            "protect-gateway-attachments",
        },
        "runtime-observer": {
            "observe-runs-api",
            "qualify-profile-route",
            "qualify-tool-surface",
            "capture-memory-posture",
            "qualify-memory-posture",
            "capture-presentation-config",
            "qualify-presentation-config",
        },
    }
    actual = {
        item["component_id"]: set(item.get("capabilities") or ())
        for item in manifest["components"]
    }
    assert actual == expected_capabilities

    forbidden_capability_fragments = (
        "authorize",
        "approve",
        "decision",
        "admit-evidence",
        "execute-effect",
        "schedule",
        "queue",
        "persist-memory",
    )
    for component_id, capabilities in actual.items():
        for capability in capabilities:
            assert not any(
                fragment in capability for fragment in forbidden_capability_fragments
            ), f"{component_id} acquired authority-like capability {capability!r}"

    bridge_root = ROOT / "hermes" / "plugins" / "pantheon-context-bridge"
    bridge_source = "\n".join(
        path.read_text(encoding="utf-8")
        for path in sorted(bridge_root.rglob("*.py"))
    )
    for forbidden in (
        'register_hook("pre_tool_call"',
        'register_middleware("tool_request"',
        'register_middleware("tool_execution"',
        "governed_effect(",
        "policy_gate",
        "DecisionRecord",
    ):
        assert forbidden not in bridge_source
