version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/.github/requirements"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "ci(governance)"
    reviewers:
      - "ifanjuang"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "ci(actions)"
    reviewers:
      - "ifanjuang"
